### ISSUE TITLE
Please add uxdesign.cc to site list

### ISSUE THREAD

**Issue by NemanSyed** [fferrin/free-medium#14]
Please add uxdesign.cc to site list
Thank you!

**Comment by fferrin** [comment]
Hi @NemanSyed . Thanks for the suggestion. I have a list of articles that I want to read someday, so I took the domain for all of them and add them to the list of domains for the extension (`uxdesign.cc` is there).

Let me know if there is another domain you want me to add. Otherwise, you can take #15 as reference and add more domains in your local clone of the extension, but it'd be great if you can report them (or create a PR) so more people can enjoy them

**Comment by NemanSyed** [comment]
Worked beautifully, and thanks for the education!
