### ISSUE TITLE
This page isn’t working

### ISSUE THREAD

**Issue by nikhil1119** [fferrin/free-medium#9]
The extension is unable to handle request somehow.

Error on browser:
freedium.cfd is currently unable to handle this request. 
HTTP ERROR 502

**Comment by blacksev** [comment]
Maybe the author can change to use https://readmedium.com

**Comment by fferrin** [comment]
Hi there. Thanks for the suggestion. I was hopping this to be a temporarly issue but since it continues from the last couple of days, and the loading times are higher, I created a `v2.0` that uses https://readmedium.com. To get this to work:
- Pull the latest changes or download the zip file with the repository content
- Go to chrome://extensions/ and upload the `extension` folder
- If you already have the repository in your computer, pull the latest changes: `git pull` and in the chrome://extensions/ page search for the extension and click the "Reload" button.

Let me know if this solves the problem for both of you so I can close the issue.

**Comment by blacksev** [comment]
@fferrin It works perfect for me, thanks for your quick updates.

**Comment by RishiikeshBalaji** [comment]
@fferrin I am unable to Load this extension in chrome browser. this is the error.

File Error: ~/Desktop/free-medium
Manifest file is missing or unreadable
Could not load manifest.

**Comment by fferrin** [comment]
Hi @RishiikeshBalaji . You have to load the `extension` folder. Follow the [installation guide](https://github.com/fferrin/free-medium?tab=readme-ov-file#installation)
